### ISSUE TITLE
В мобильной версии нужно исправить вёрстку

### ISSUE THREAD

**Issue by librarian** [whatifrussian/website#491]
Смещен указатель не мобиле (не по центру).

**Comment by Totktonada** [comment]
Никит, можешь показать на скриншоте? Я помню, что уже как-то спрашивал, но сейчас снова не могу взять в толк, о чем речь.

**Comment by librarian** [comment]
![screenshot from 2015-01-14 18 12 52](https://cloud.githubusercontent.com/assets/129251/5740965/314c0302-9c19-11e4-9ed8-45e83fea376f.png)
